name: Test

on:
  push:
    branches:
      - master
    tags-ignore:
      - v*

  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '10.x'
      - run: yarn
      - run: yarn test
      - run: yarn codecov

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '10.x'
      - run: yarn
      - run: yarn lint
      - run: yarn typecheck
      - run: yarn build

  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '10.x'
      - run: yarn
      - uses: wagoid/commitlint-github-action@v3
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules
